### ISSUE TITLE
Add Equella Sources from equella--master/6-4-edalex branch

### ISSUE THREAD

**Issue by smclaughlin520** [Equella-Digital-Repository/Equella#1]
New Master = 6-4-edalex
TDC branch (6-4-qa3) included as well

## To Prevent Disclosing Secrets

- [x] Step 1: Start with the ~~6.4.2 tag~~ `6-4-edalex` branch
- [x] Step 2: Push to bitbucket.org/equellateam as `clean-me-up` branch
- [x] Step 3: Review all config resources -- properties, XML, certificates, etc. -- and remove any secrets and other items shouldn't be displayed public
- [ ] ~~Step 4: Cherry-pick additional commits from the Edalex branch~~
- [x] Step 5: Remove all history
- [x] Step 6:  Push to this repo as `master`

**Comment by drewwills** [comment]
Benito to take step #1 and put it in a prive repo.  Please share it with @msultzaberger, who will take step #2.

**Comment by doolse** [comment]
I'm happy with this approach, probably best if someone from edalex does 2. as we know the passwords to look for. I'm happy to put my hand up to do that. I've just completed #2 so it might make sense if I pushed the initial repo with those changes too?

**Comment by bjagg** [comment]
Pearson repos that started with 'equella' were uploaded to BitBucket. Since I do not have access to the Unicon account on BitBucket, I created a basic team around these repos. Unfortunately, there is a 5 member limit. I was able to add Doolse by dropping Shelley.

**Comment by bjagg** [comment]
To delete history, This is a good solution: http://stackoverflow.com/questions/13716658/how-to-delete-all-commit-history-in-github

**Comment by bjagg** [comment]
Instead of deleting history at Step 1a, we can perform that step as we move from BitBucket to GitHub.

**Comment by drewwills** [comment]
@bjagg -- That's a great plan.

Ideally, the first version of the sources in GitHub would be the 6.4.2 tag exactly, EXCEPT with secrets scrubbed.  Starting with that branch, we can `git cherry-pick` the commits from the Edalex branch.

**Comment by bjagg** [comment]
Created 'clean-me-up' branch in equella---master based off of 'release/6.4-edalex'. The branches are as follows:
  origin/65/feature/EQ-2374-move-workflow-task
  origin/65/feature/EQ-2381-random-workflow-notifications
  origin/65/feature/EQ-2551_email-templates
  origin/65/feature/EQ-2606-skip-within-mod-selected
  origin/65/feature/EQ-2639-dnd-onto-attachments-control-in-wizard
  origin/65/feature/EQ-2641-zip-package-options-streamline
  origin/6x/task/EQ-350-iterable-db-results
  origin/HEAD -> origin/master
  origin/TDC/6.4-QA1
  origin/archive/6x/feature/icodeon
  origin/archive/6x/feature/lucene4.7
  origin/archive/6x/feature/s3
  origin/archived/bugfix/canvas-content-item-placements
  origin/archived/feature/UTS
  origin/archived/feature/devry
  origin/archived/feature/tafeqld-6.4-QA2
  origin/archived/feature/uow-workflow-api-QA2
  origin/bugfix/EQ1502_2393_2197
  origin/bugfix/TDC
  origin/master
  origin/pluginfix/flinders
  origin/rebase_master_trial
  origin/release/6.2
  origin/release/6.3
  origin/release/6.4
  origin/release/6.4-QA2
  origin/release/6.4-QA3
  origin/release/6.4-edalex
  origin/release/TDC-6.4-QA3

**Comment by smclaughlin520** [comment]
Edalex team will be working on Step 3

**Comment by drewwills** [comment]
@doolse -- If you haven't already, please begin scrubbing secrets and sensitive items from all source files in the `clean-me-up` branch (equellateam in bitbucket).

This item is a blocker.  It would be immensely helpful if you could...
  - Take care of it ASAP
  - Tell us something (up front) about when you think it will be completed

Thank you!

**Comment by doolse** [comment]
@drewwills I should be able to get this done today in a few hours

**Comment by doolse** [comment]
Scrubbing is now complete: 
"equella---master/clean-me-up" HEAD is scrubbed and points to HEAD commits of
"platform/clean-me-up" and "equella---rest-interfaces/clean-me-up"

**Comment by drewwills** [comment]
Thanks @doolse!

@bjagg -- Can you now...
  - Take the `clean-me-up` branch without history
  - Push it to this repo as `master`?

**Comment by bjagg** [comment]
```
git checkout --orphan clean-me-up
git add -A
git commit -am "Clean history"
git branch -D master
git branch -m master
git push -f origin master
```

**Comment by bjagg** [comment]
https://bitbucket.org/equellateam/equella-master/commits/all

Master is clean, but we still have history in the other branches. When should we delete those?

**Comment by drewwills** [comment]
@bjagg -- Nice process.  A couple questions...

  - What's the 'a' for in `git commit -am "Clean history"`
  - In the end, are you really pushing to the `origin` repo?  (Is the bitbucket repo non-origin?)

**Comment by drewwills** [comment]
@bjagg -- Never!

At this time, we are not planning to move more than one branch to GitHub.  (They can stay in bitbucket.)  We can look at them case-by-case, if needed.

**Comment by bjagg** [comment]
Okay, we are now on the same page. I restored the BitBucket repo and an working on the clean repo that is going to GitHub.

**Comment by bjagg** [comment]
Pushed the clean branch to GitHub as the first and only commit.

Note: I removed:

1. .gitmodules since it references Pearson's source server
2. Source/Build/cacerts in case it had sensitive data

Please feel free to add these files back as needed. I only kept them out due to an abundance of caution.
