### ISSUE TITLE
Merge "Platform" and "Interface" git submodules into main Equella repo

### ISSUE THREAD

**Issue by doolse** [Equella-Digital-Repository/Equella#17]
The main Equella repo uses a couple of shared repos which were used for a few other Equella related projects but there really is no need to have separate repos for them as it just complicates things.

## Both of these repos must follow the same process we used with equella--master

Follow these steps to Prevent Disclosing Secrets

- [x] Step1: In the equellateam Bitbucket repos (Platform & Interface), create a `clean-me-up` branch based on the tip of 6-4-edalex (does this branch exist in these?)
- [x] Step 2: Review all config resources -- properties, XML, certificates, etc. -- and remove any secrets or sensitive items (push these commits to the `clean-me-up` branch)
- [x] Step 3: Remove the corresponding submodule in the GitHub Equella repo;  add sources directly and **without history**;  push to `master`

**Comment by drewwills** [comment]
Good idea -- thanks for adding this ticket.

**Comment by ddelblanco** [comment]
In the equella-master root folder we have the .gitmodules file with this that connects master with these 4 repos. Meanwhile we don't merge all in one repo, We need to change that to point to our bitbucket now:

[submodule "Platform"]
        path = Platform
        url = ssh://git@bitbucket.pearson.com/eq/platform.git
[submodule "OfficeIntegration"]
        path = Source/Integration/office-integration
        url = ssh://git@bitbucket.pearson.com/eq/equella---office-integration.git
[submodule "ConversionLibs"]
        path = Installer/data/server/conversion
        url = ssh://git@bitbucket.pearson.com/eq/equella---conversion-libs.git
[submodule "Interface"]
        path = Interface
        url = ssh://git@bitbucket.pearson.com/eq/equella---rest-interfaces.git


Based on this, should we merge too the conversion and the office integration??????

**Comment by ddelblanco** [comment]
If someone wants to change the local .gitignore to bring the full code to their local branch, this is the content of the new .gitignore. I don't commit it because these projects will be merged very soon:

[submodule "Platform"]
        path = Platform
        url = ssh://git@bitbucket.org/equellateam/platform.git
[submodule "OfficeIntegration"]
        path = Source/Integration/office-integration
        url = ssh://git@bitbucket.org/equellateam/equella-office-integration.git
[submodule "ConversionLibs"]
        path = Installer/data/server/conversion
        url = ssh://git@bitbucket.org/equellateam/equella-conversion-libs.git
[submodule "Interface"]
        path = Interface
        url = ssh://git@bitbucket.org/equellateam/equella-rest-interfaces.git

**Comment by doolse** [comment]
@drewwills @bjagg I will create the "clean-me-up" branches in both "Platform" and "Interface" based on the commits referenced in "release/6.4-edalex" and scrub them

**Comment by doolse** [comment]
Both Platform and Interface "clean-me-up" branches are scrubbed now (Platform didn't have any sensitive data).

**Comment by drewwills** [comment]
Excellent @doolse!

Who wants to tackle removing the submodules and replacing them with sources?

**Comment by doolse** [comment]
I'm keen to take that on :+1:

**Comment by drewwills** [comment]
@doolse -- What's the ETA on this task?  (I guess I thought it would happen last night.)

**Comment by doolse** [comment]
It did happen yesterday, it was put into a "nonexus" branch but i've merged it now. There was a couple of things I noticed which I'll make issues for.
