### ISSUE TITLE
Work out what to do about hardcoded SHA256 hash salt

### ISSUE THREAD

**Issue by doolse** [Equella-Digital-Repository/Equella#27]
The code contained a hardcoded salt for passwords, for now instead of it being hardcoded it has to be passed into equella as a system property "equella.salt".

**Comment by drewwills** [comment]
Has this change already been made?  (Can the ticket be closed?)  Was the old salt removed from the history?

- [ ] Update the documentation to cover this configuration setting

**Comment by emcgarrahan** [comment]
Decision 4.12.17 - Make the salt default back to the original hardcoded salt if the property is not supplied
