### ISSUE TITLE
Upgrade libraries that are in Maven

### ISSUE THREAD

**Issue by emcgarrahan** [Equella-Digital-Repository/Equella#28]
https://docs.google.com/spreadsheets/d/1GYyQ2jdw9IKccQDVt-cpcvgJuI5MuCUgOAzCkr4JIYw/edit?usp=sharing

Refer to the Maven tab of the above spreadsheet.

**Comment by doolse** [comment]
All of the libraries from the "Maven" tab have been upgraded to use the versions found in Maven Central.

**Comment by drewwills** [comment]
@doolse -- I don't see any commits that relate to this issue... how does the build process pull those libraries from M2 Central?
